# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import leetcode682 as module_0

#@pytest.mark.xfail(strict=True)
def test_case_0(): # FAILED test_leetcode682.py::test_case_0 - ValueError: invalid literal for int() with base 10: '#'
    solution_0 = module_0.Solution()
    str_0 = "9#"
    solution_0.calPoints(str_0)


#@pytest.mark.xfail(strict=True)
def test_case_1(): # FAILED test_leetcode682.py::test_case_1 - ValueError: invalid literal for int() with base 10: 'XhW<P'
    str_0 = "XhW<P"
    list_0 = []
    solution_0 = module_0.Solution()
    int_0 = solution_0.calPoints(list_0)
    str_1 = "wSZF)<[wP\r+\x0bOTG2gp"
    list_1 = [str_0, str_1, str_1, str_0]
    solution_0.calPoints(list_1)


def test_case_2(): #PASSED
    solution_0 = module_0.Solution()


#@pytest.mark.xfail(strict=True)
def test_case_3(): # FAILED test_leetcode682.py::test_case_3 - IndexError: pop from empty list
    solution_0 = module_0.Solution()
    str_0 = "C"
    solution_0.calPoints(str_0)


#@pytest.mark.xfail(strict=True)
def test_case_4(): # FAILED test_leetcode682.py::test_case_4 - IndexError: list index out of range
    str_0 = "D"
    list_0 = []
    solution_0 = module_0.Solution(*list_0)
    solution_0.calPoints(str_0)


#@pytest.mark.xfail(strict=True)
def test_case_5(): # FAILED test_leetcode682.py::test_case_5 - IndexError: list index out of range
    str_0 = "+"
    list_0 = [str_0]
    solution_0 = module_0.Solution()
    solution_0.calPoints(list_0)
